name: CI Pipeline for Calculator

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t calculator-test ./BE

      - name: Run tests
        run: |
          docker run calculator-test pytest --junit-xml=report.xml

      - name: Upload test report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/report.xml'

      - name: Log in to Azure Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t judevops.azurecr.io/christoffer_lundh-calculator ./BE
          docker push judevops.azurecr.io/christoffer_lundh-calculator
