name: CI Pipeline for Calculator

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r BE/requirements.txt

      - name: Start the REST API
        run: |
          python BE/calculator.py --rest &

      - name: Run Unit and API tests
        run: |
          export PYTHONPATH=.
          pytest --junit-xml=report.xml
          
      - name: Upload test results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          name: test-report
          path: report.xml

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        run: |
          docker build -t judevops.azurecr.io/christoffer_lundh-calculator ./BE
          docker push judevops.azurecr.io/christoffer_lundh-calculator

